### ISSUE TITLE
Error: [alova]The user aborted a request

### ISSUE THREAD

**Issue by jamessawyer** [alovajs/alova#195]
### 请详细描述bug

本地开发我自己的机器不会出现这个取消请求的问题，同事的电脑会出现。打包上线之后，线上必出现取消请求的问题。
代码片段：
```typescript
export const getCode = (req: any) =>
    alovaInstance.Post<any>('/xxx/getCode', req, {
        transformData(rawData) {
            if (!rawData) return []

            return rawData
                ?.filter(item => item.code != '-1' && item.code !== null)
                .map(item => ({
                  ...item
                }))
        },
    })
```
调用：
```vue
import { useWatcher } from 'alova'

const {
    onSuccess,
    send: sendList,
    data: allOptions,
} = useWatcher(() => getCode({ ...formState }), [formState], {
    immediate: false,
})

const getData = async () => {
   // 其余逻辑
   //  ...
    allOptions.value = await sendList()
}

onMounted(() => {
    getData()
})
```

报错信息：
```bash
Error: [alova]The user aborted a request
 at S8r(index.332842f3.js:6117:461)
 at C8r([index-332](index.332842f3.js:6117:)518)
 at index.332842f3.js:6117:865
 at async Promise.all (index 0)
 at async f (index-76618190.js:4:11544)
```

### 复现步骤

1. 进入页面第一次自动取消请求
2. 修改表单下拉框，请求又能成功发送

### alova 版本

2.9.3

**Comment by JOU-amjs** [comment]
@jamessawyer 我在2.11.0中发现了这个问题，这可能需要你们先回退到2.10.x或之前的就可以正常使用了。我会尽快解决这个问题

**Comment by jamessawyer** [comment]
好的，我试一试。但是这个问题可能的原因是什么？ 感觉之前用的好好的，突然就有问题了

**Comment by jamessawyer** [comment]
原来下载npm包使用 '^xx.xx.xx' 形式，默认会将 'Major.Minor.Patch' 中的 `Minor` 升级到最新的

**Comment by JOU-amjs** [comment]
@jamessawyer 你可以把“^”改为“~”，这样就可以限制在2.10.x了

**Comment by jamessawyer** [comment]
嗯，已经改了，2.10.x版本没有发现这个问题

**Comment by JOU-amjs** [comment]
好的，改好这个问题我会在这里通知的

**Comment by JOU-amjs** [comment]
@jamessawyer 已修复，升级到v2.11.1解决
