### ISSUE TITLE
如何在纯 html 内用呢？

### ISSUE THREAD

**Issue by JOU-amjs** [alovajs/alova#37]
### Discussed in https://github.com/alovajs/alova/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **jufjzq** March 31, 2023</sup>
```html
<script src="https://unpkg.com/alova/dist/alova.umd.min.js"></script>
<script src="https://unpkg.com/alova/dist/adapter/globalfetch.umd.min.js"></script>

<script>
  const alovaInstance = alova.createAlova({
    baseURL: 'localhost:3000',
    requestAdapter: window.GlobalFetch(),
  });
  const { data, loading, error } = alova.useRequest(
    () => alovaInstance.Get('/api'),
    {
      initialData: [],
    }
  )
  console.log(data);
</script>
```
F12报错
```js
Uncaught TypeError: Cannot destructure property 'create' of 'm(...)' as it is undefined.
    at fe (alova.umd.min.js:1:6750)
    at e.useRequest (alova.umd.min.js:1:8881)
    at （索引）:44:42
```</div>

**Comment by JOU-amjs** [comment]
感谢你的反馈！！！我们已修复了这个问题，可以按以下两个步骤来操作：
1. 升级到alova 2.0.16及以上版本
2. 按如下方式编码：
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
</head>
<body>

</body>
<script src="https://unpkg.com/alova/dist/alova.umd.js"></script>
<script src="https://unpkg.com/alova/dist/adapter/globalfetch.umd.js"></script>
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
<script src="https://unpkg.com/alova/dist/hooks/vuehook.umd.js"></script>
<script>
  const alovaInstance = alova.createAlova({
    baseURL: 'http://localhost:3000',

    // 需要设置statesHook
    statesHook: window.VueHook,
    requestAdapter: window.GlobalFetch(),
  });
  const { data, loading, error } = alova.useRequest(
    () => alovaInstance.Get('/api'),
    {
      initialData: [],
    }
  )
  console.log(data);
</script>
</html>
```
